# Source - https://stackoverflow.com/a
# Posted by Azmisov, modified by community. See post 'Timeline' for change history
# Retrieved 2025-11-13, License - CC BY-SA 4.0

name: Update pkg.go.dev

on:
  push:
    tags:
      - '*'

jobs:
  update-pkg-go-dev:
    runs-on: ubuntu-latest
    steps:
      # see https://pkg.go.dev/about#adding-a-package
      - name: Update pkg.go.dev
        run: |
          ESCAPED_MODULE=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')
          curl https://proxy.golang.org/github.com/$ESCAPED_MODULE/@v/$GITHUB_REF_NAME.info
